const express = require("express");
const router = express.Router();
const AdminRoutes = require("./../domains/AdminRoutes");
const HotelRoutes = require("./../domains/HotelRoutes");
const ClientRoutes = require("./../domains/ClientRoutes");
const OTPRoutes = require("./../domains/OTPVerificationRoutes");
const ReservationRoutes = require("./../domains/ReservationRoutes");
const RoomServiceRoutes = require("./../domains/RoomServiceRoutes");
const MessagesRoutes = require("./../domains/Messages/routes");
router.use("/admin", AdminRoutes);
router.use("/hotel", HotelRoutes);
router.use("/client", ClientRoutes);
router.use("/otp", OTPRoutes);
router.use("/reservation", ReservationRoutes);
router.use("/roomservice", RoomServiceRoutes);
router.use("/messages", MessagesRoutes);
module.exports = router;
