const express = require("express");
const router = express.Router();
const AdminRoutes = require("./../domains/admin");
const HotelRoutes = require("./../domains/hotel");
const ClientRoutes = require("./../domains/client");
const OTPRoutes = require("./../domains/otp_verification");
const ReservationRoutes = require("./../domains/reservation");
const RoomServiceRoutes = require("./../domains/roomservice");
router.use("/admin", AdminRoutes);
router.use("/hotel", HotelRoutes);
router.use("/client", ClientRoutes);
router.use("/otp", OTPRoutes);
router.use("/reservation", ReservationRoutes);
router.use("/roomservice", RoomServiceRoutes);
module.exports = router;
